### ISSUE TITLE
Websocket: Aktualisierte WantToSpeak liste wird nicht an client gesendet

### ISSUE THREAD

**Issue by schalterDev** [die-gruppe-c/mop-backend#4]
Wenn ein Client zum Beispiel diesen Befehl sendet `wantToSpeak:1` bekommt dieser keine aktualisierte wantToSpeakList geschickt.

Erst wernn der Modeartor diese Meldung dran nimmt bekommt der Client wieder eine aktualisierung der wantToSpeakList geschickt.

**Comment by schalterDev** [comment]
Das gleiche Verhalten bei folgendem Befehl: `wantNotToSpeak`

**Comment by c-roth** [comment]
Teilnehmer sollen die Meldungen gar nicht sehen. Dass die Teilnehmer die WantToSeakList geschickt bekommt ist ein Fehler der im nächsten Push behoben ist. Teilnehmer sehen nur die Redeliste.

**Comment by schalterDev** [comment]
Und wie bekommt der Nutzer mit, dass das Backend kapiert hat, dass er sich gemeldet hat?
