### ISSUE TITLE
Frage: Soll der Benutzer die Möglichkeit haben seinen Beitrag selbst zu beenden

### ISSUE THREAD

**Issue by schalterDev** [die-gruppe-c/mop-backend#5]
siehe Titel

**Comment by c-roth** [comment]
Ja ich würde sagen dass ein Benutzer wenn er an der Reihe ist die gleiche Anzeige sieht wie der Moderator mit aktueller zeit pause und stop. Wenn ein Anderer redet sollten alle Teilnehmer sehen wer spricht und wie lange schon.
